---
abstract: 'Tests files for their content based on their file extension'
author:
  - 'Moritz Onken'
build_requires:
  File::Temp: 0
  Module::Build: 0.3601
  Test::Harness: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-File-Content
provides:
  Test::File::Content:
    file: lib/Test/File/Content.pm
    version: v1.0.0
requires:
  Exporter: 0
  File::Find: 0
  Path::Class::File: 0.23
  Test::Harness: 3.22
  Test::More: 0.96
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-File-Content
  homepage: http://search.cpan.org/dist/Test-File-Content/
  repository: git://github.com/monken/p5-test-file-content.git
version: 1.0.0
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@Filter/CompileTests'
      version: 1.103030
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Filter/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@Filter/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@Filter/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/PodCoverageTests'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@Filter/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Filter/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Filter/PruneFiles'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Filter/Prepender'
      version: 1.103470
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Filter/Bugtracker'
      version: 1.102670
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@Filter/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Filter/Repository'
      version: 0.17
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Filter/MetaProvides::Package'
      version: 1.12044908
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Filter/ModuleBuild'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Filter/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/Git/Check'
      version: 1.103520
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/Git/Commit'
      version: 1.103520
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/Git/Tag'
      version: 1.103520
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/Git/Push'
      version: 1.103520
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200000
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200000
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200000
